version: '3'

services:
  api:
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
    environment:
      NODE_ENV: development
    depends_on:
      - database
  frontend:
    build: ./client
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
    depends_on:
      - api
