version: '3'

services:
  api:
    build: ./server
    ports:
      - '6524:6524'
    volumes:
      - ./:/app
    environment:
      NODE_ENV: production
    depends_on:
      - database
  frontend:
    build: ./client
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    environment:
      NODE_ENV: production
    depends_on:
      - api
