name: deploy-docker-dist

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t my-image .
          docker tag my-image ${{ secrets.DOCKER_USERNAME }}/my-image:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest
