name: normal-build-dist
on:
  push:
    branches:
      - develop
jobs:
  build-dist-job:
    runs-on: ubuntu-latest
    steps:
      # 切换代码分支
      - name: checkout-release-code
        uses: actions/checkout@v3

      # 安装nodejs
      - name: add-node-env
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # 缓存依赖
      - name: Cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      # 安装pnpm
      - name: install pnpm
        run: npm install -g pnpm

      # 安装依赖
      - name: Installing Dependencies
        run: pnpm install

      # build依赖
      - name: Build dist
        # run: |
        #   npm run build:client && npm run build:pilot && npm run build:server
        run: npm run build:server
      - name: echo tasks
        run: echo "build success"

  deploy-dist-job:
    runs-on: ubuntu-latest
    needs: build-dist-job
    steps:
      # - name: upload client dists
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     # SSH_PRIVATE_KEY为准备工作步骤三中生成密钥对里的私钥
      #     SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_TOKEN }}
      #     # 指定当前目录中要上传的内容
      #     SOURCE: 'packages/client/dist/'
      #     # 指定上传到部署机器的哪个目录下
      #     TARGET: '/var/www/html/projects/admin-deploy/'
      #     # 上传前指令，此处用于清空TARGET下的文件
      #     # ARGS: "-avzr --delete"
      #     # REMOTE_HOST为机器的公网IP
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     # REMOTE_USER为登录机器时用到账号名
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}

      - name: upload server dists
        uses: easingthemes/ssh-deploy@main
        env:
          # SSH_PRIVATE_KEY为准备工作步骤三中生成密钥对里的私钥
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_TOKEN }}
          # 指定当前目录中要上传的内容
          SOURCE: 'packages/server/dist/'
          # 指定上传到部署机器的哪个目录下
          TARGET: '/var/www/html/backends/pilot-server/'
          # 上传前指令，此处用于清空TARGET下的文件
          # ARGS: "-avzr --delete"
          # REMOTE_HOST为机器的公网IP
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # REMOTE_USER为登录机器时用到账号名
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
